### ISSUE TITLE
Add LiipImagineBundle integration 

### ISSUE THREAD

**Issue by ryall** [V-labs/VlabsMediaBundle#1]
I'd suggest replacing the `ImageManipulator` with LiipImagineBundle integration (https://github.com/liip/LiipImagineBundle).

**Comment by choomz** [comment]
In fact, I did not know this bundle. I'll look at what can be done in terms of integration. What is certain is that I do not want to lose the opportunity to request a resize from twig.

**Comment by choomz** [comment]
Can you give me the features you would like to see in this bundle? I see in LiipImagine a lot of features that I do not want to connect with my bundle since I already give an implementation.

If you want to manage more filters than just resizing as actually, I can set up events that will give you access to the image to do what you want, with the ability to disable the ImageManipulator.

What do you think about it?

**Comment by jcrombez** [comment]
It would be very usefull to be able to do like so : 

{{ media(user.avatar, 'image', { resize : { 'width' : 300 } }) }}

And get a thumbnail keeping the ratio of the image.

Also, an option to change the behavior, and not having a crop effect. Then, when you specify a resize 100x100 (for example), a 400x800 image would become a 50x100, and a 800x400 would become a 100x50.

This second use case is less frequently needed, but the first is really important for thumbnails, cropping is rarely wanted for thumbs.

**Comment by choomz** [comment]
Yes you are right. This part needs to be improved.

But actually I don't have the time to fix it. I want the bundle to be able to handle different media representation in front end. There is a lot of work to handle it and i'm waiting for a real use case to write it.

Actually you can still override the ImageManipulator class wich handle the resizing process.

**Comment by jcrombez** [comment]
I'm probably going to try to override ImageManipulator, maybe i could create a PR out of this ? Except if you plan on doing it a different way ?

**Comment by choomz** [comment]
Yes you can make a PR that enhance the actual behavior of the ImageManipulator. You probably also have to remove some tests in the twig extension to disable the mandatory height parameter in the filter.

It would be cool if we can keep the crop behavior too.

The way I want to do at the end may change the bundle API, so it won't be right now :)

**Comment by jcrombez** [comment]
Okay i'll see what i can do to add a behavior instead of replacing the cropping.

**Comment by jcrombez** [comment]
What do you think of the following syntax : 

### Crop the media :

```
{{ media(user.avatar, 'image', { 'filter': 'crop', 'width': 300 }) }}

{{ media(user.avatar, 'image', { 'filter': 'crop', 'height': 300 }) }}

{{ media(user.avatar, 'image', { 'filter': 'crop', 'width': 300, 'height': 300 }) }}
```

### Resize the media width keeping the size ratio :

1000x2000 => 150x300
2000x1000 => 150x300

```
{{ media(user.avatar, 'image', { 'filter': 'resize', 'width': 300 }) }}
```

### Resize the media keeping the ratio and largest possible side :

1000x2000 => 150x300
2000x1000 => 300x150

```
{{ media(user.avatar, 'image', { 'filter': 'resize', 'width': 300, 'height': 300 }) }}
```

**Not very usefull, maybe later :** 

### Resize the media ignoring the ratio  :

1000x2000 => 300x300
2000x1000 => 300x300

```
{{ media(user.avatar, 'image', { 'filter': 'resize', 'width': 300, 'height': 300, 'force': true }) }}
```

### Resize the media ignoring the ratio and keeping the other side the same size :

1000x2000 => 1000x300
2000x1000 => 2000x300

```
{{ media(user.avatar, 'image', { 'filter': 'resize', 'width': 300, 'force': true }) }}
```

**Comment by choomz** [comment]
It looks good. But it introduces some question about the params management in the third media() helper param.

I think we should be able to use a 2 dimensions array which takes the action keyword as a key. All optionnals params are a second dimension array.

This way we can seperate filters like image manipulator or pdf thumb manager or whatever ...

What do you think about it ? 

Or better, use a parameter bag symfony class...

I'll be back in two days now :)

**Comment by jcrombez** [comment]
Yes, managing parameters when handling a lot more different types of media will become easier this way for sure.

Here is an adjusted version of my previous proposition :

### Crop the media :

```
{{ media(user.avatar, 'image', { 'crop' : { 'width': 300 }}) }}

{{ media(user.avatar, 'image', { 'crop' : { 'height': 300 }}) }}

{{ media(user.avatar, 'image', { 'crop' : { 'width': 300, 'height': 300 }}) }}
```

### Resize the media width keeping the size ratio :

1000x2000 => 150x300
2000x1000 => 150x300

```
{{ media(user.avatar, 'image', { 'resize': {'width': 300 }}) }}
```

### Resize the media keeping the ratio and largest possible side :

1000x2000 => 150x300
2000x1000 => 300x150

```
{{ media(user.avatar, 'image', { 'resize': {'width': 300, 'height': 300 }}) }}
```

I'll go for this and prepare a PR for when you'll be back and alcohol-free, next year  :-p

**Comment by choomz** [comment]
To answer to the initial request for this issue, which was to use liip imagine bundle as a filter for images, I pushed today version 1.1 of the bundle that modifies the twig API.

The bundle is now using filters, which can be left aside in favor of those of another bundle as LIIP.

Here are links to the new documentation : 

[Templating](https://github.com/V-labs/VlabsMediaBundle/blob/master/Resources/doc/3-templating.md)
[Filters](https://github.com/V-labs/VlabsMediaBundle/blob/master/Resources/doc/6-custom-stand-alone-filters.md)
[Upgrade file](https://github.com/V-labs/VlabsMediaBundle/blob/master/UPGRADE.md)

I'm closing this issue.
