### ISSUE TITLE
Not possible to add images directly

### ISSUE THREAD

**Issue by lsv** [V-labs/VlabsMediaBundle#11]
Its not possible to add images without a form.
Fx via fixtures

[ErrorException]  
Notice: Undefined variable: classConfig in vendor/vlabs/media-bundle/Vlabs/MediaBundle/Handler/HandlerManager.php line 84

Do you have any fixes for this?

Im using this code in my fixture

```
use Symfony\Component\Finder\Finder;

$finder = new Finder;
$finder->files()->in($path);
foreach($finder as $file) {
   $img = new Entity\Image();
   $img->setContentType('image/jpeg');
   $img->setCreatedAt(new \DateTime());
   $img->setName($file->getFilename());
   $img->setPath($file->getPath());
   $img->setSize($file->getSize());

   $manager->persist($img);
   $manager->flush();
}
```

**Comment by choomz** [comment]
Hi, you should use the master branch, this bug has been fixed : https://github.com/V-labs/VlabsMediaBundle/commit/e1926a37a21b5588c3bf9a3158f811befb29a9a1

**Comment by lsv** [comment]
Nice :) - and it works
