### ISSUE TITLE
createdAt property in abstract class

### ISSUE THREAD

**Issue by Spomky** [V-labs/VlabsMediaBundle#16]
I saw that you set a property createdAt in the class BaseFile.
This property is not related to the media themselves.

I think you should let the developers decide whether they need or not such a property.
If they need it, let them implement it in their entity.

**Comment by choomz** [comment]
Yes you are right. The BaseFile class is provided as a 'default' class. The real business is the BaseFileInterface. If you want to handle your own properties in your media classes, just skip the BaseFile class and implement the BaseFileInterface in your objects.

The properties that are defined in this interface are mandatory, and as you can see, createAt is not one of them.
Hope it helps.

**Comment by Spomky** [comment]
Thank you for your answer.
Yes it helps me, I thought BaseFile were mandatory for all entities.
I have created my own BaseFile and it works fine.
