### ISSUE TITLE
required=true when editing and add_del option with new entity

### ISSUE THREAD

**Issue by rbaarsma** [V-labs/VlabsMediaBundle#19]
Hi,

I've just installed your bundle. Looks great so far! I saw 2 possible enhancements. Wanting to make my form user-friendly, I don't want the user to see the delete option when creating a new entity. 

Similarly it's annoying for the user that if the image is required, but already uploaded and showing, that the user needs to upload a new image (overwriting the existing). 

I think I tackled both issues for you by changing Vlabs\MediaBundle\Form\Type\FileType

Although in some use-cases this could lead to problems when people actually want the above stated behavior.. 

Kind regards,
Rein

class FileType extends AbstractType
{
    // ...
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // check if form is related to entity and if that entity has an ID
        if (is_object($builder->getData()) && method_exists($builder->getData(), 'getId'))
        {
            if ($builder->getData()->getId() === null)
            {
                // remove delete button on a new entity
                if ($options['add_del'])
                    $options['add_del'] = false;
            }
            else
            {
                // remove required on existing entity
                if ($options['required'] === true)
                    $options['required'] = false;  
            }
        }
                // ...

**Comment by choomz** [comment]
Hi,

You're right. Maybe we could make another test in the BaseFileListener ?

https://github.com/V-labs/VlabsMediaBundle/blob/master/EventListener/BaseFileListener.php#L67

We could also add a show_on_create option in the checkbox type.

Does it helps ?

**Comment by choomz** [comment]
Closed due to inactivity.
