### ISSUE TITLE
[New feature] Ink File Picker

### ISSUE THREAD

**Issue by lsv** [V-labs/VlabsMediaBundle#21]
Would it be possible to somehow integrate [Ink File Picker](https://www.inkfilepicker.com/) ?

API: https://developers.inkfilepicker.com/docs/web/

Why you may ask...
1: It supports picking files from a long list of providers (computer, facebook, dropbox, flickr and many others)

2: It have a nice [drag'n'drop](https://developers.inkfilepicker.com/docs/web/#widgets-pick) (click "Pick File" for a demo)

3: It supports multiple file upload

4: Everything is javascript.

**Comment by choomz** [comment]
Hello,

I'm sorry but actually I won't add dependency with a paid lib. Even if it was free, I wan't to keep this bundle as simple as possible without adding third party libs.

I know that javascript uploading is a wanted feature, but I do not have a solution atm.

**Comment by lsv** [comment]
I can see your point.

By the way, ink file picker is free for personal use, but does not include S3 storage or image conversion

Free Plan
For personal projects, we offer a free plan for uploading 500 files/month with a max file size of 20 MB.
The free plan does not include customizing the logo or CSS of the dialog, S3 storage, or image conversion.

**Comment by choomz** [comment]
Yeah I know, but actually this bundle is not used only for personal use :)

You are talking about S3. The next update will be a better handling for filesystems with the last version of gaufrete.
I also added media events to tweak upload on different filesystems.

I'm actually working on resize, with format handling from config.

And still no js .. :)

**Comment by lsv** [comment]
By the way, is it possible to have multiple medias on a single entity?
I only used your bundle where I needed 1 media on a entity, but now im looking for one than can handle unlimited medias/files on a single entity
