### ISSUE TITLE
Issue with an ArrayCollection

### ISSUE THREAD

**Issue by kosssi** [V-labs/VlabsMediaBundle#27]
Hello

Thinks for your bundle ;)

I test it yesterday and i would like to know if it's possible to use it with an ArrayCollection with prototype ?

**Comment by daslicht** [comment]
I would also like to know how to upload and link multiple images to one "Article"

**Comment by choomz** [comment]
I did an exemple for a collection mapping. Actually you need an intermediate entity to embed it as a collection.
Check it (it's for a galery) : https://gist.github.com/choomz/4948099

Here it's a full exemple of forms & controller: https://gist.github.com/choomz/6b026aed3d09b4581c78

Hope it helps

**Comment by kosssi** [comment]
Thinks you.

I thinks you can write this in documentation of the bundle ;)
