### ISSUE TITLE
How to add custom properties to an Image ?

### ISSUE THREAD

**Issue by daslicht** [V-labs/VlabsMediaBundle#28]
Hello,
Ive tried to add the following to my Image Class:

``` PHP
    /**
     * Defines if the current picture should be shown as thumb in list
     * @var boolean $isThumb
     */
    private $isThumb;
```

When I try to generate getter/setters they are not generated.
I created them manually but when I run:

php app/console doctrine:schema:update --force

The Database Scheme do not change ?

**Comment by choomz** [comment]
Hi,

You need to map the field to doctrine ... check the documentation http://symfony.com/doc/current/book/doctrine.html#add-mapping-information

**Comment by daslicht** [comment]
thank you
