### ISSUE TITLE
question about MediaBundle

### ISSUE THREAD

**Issue by smramirez** [V-labs/VlabsMediaBundle#29]
Hello, first I want to congratulate you for this excellent bundle. I would like to ask you a simple question about MediaBundle, basically how to validate that  only can be uploaded files of an specific  mime/type and with a maximum size. Since none of the attributes in the used entities has the file type, where I can put this kind of validation or constraints.

**Comment by choomz** [comment]
Hi, you should try to use Symfony validators on the base file (your media property). The @Valid() constraint can also helps you.

Hope it helps.
