### ISSUE TITLE
Documentation order problem

### ISSUE THREAD

**Issue by jcrombez** [V-labs/VlabsMediaBundle#3]
You can't update your doctrine schema before the configuration step, or you get the following error : 

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
The child node "mapping" at path "vlabs_media" must be configured.

The documentation should be reordered.

**Comment by choomz** [comment]
Yes you are write. Fixed now. I also added some requirements in composer.json file.
Thanks for your feedback. Note that you can also submit small PRs to fix that :)
