### ISSUE TITLE
Can I use another Document class?

### ISSUE THREAD

**Issue by mlaptas** [V-labs/VlabsMediaBundle#35]
Hi. 

I have defined my own document classes, f.e. ImageFile, PdfFile - they extend AbstractFile class. How can I use my own classes in User document (it has inside such definition:
@ODM\ReferenceOne(targetDocument="MyOwnBundle\Document\File\AbstractFile") protected $avatar;

Regards, Marek

**Comment by choomz** [comment]
Hi, did you try to reference you own FQDN class : MyOwnBundle\Document\File\ImageClass instead of AbstractClass ?

**Comment by choomz** [comment]
Closed due to inactivty
