### ISSUE TITLE
documentation in yaml.

### ISSUE THREAD

**Issue by piux** [V-labs/VlabsMediaBundle#39]
where can i find documentation for yaml for extending the baseclass, im going to use app/console doctrine:mapping:convert yml destination-dir/.

**Comment by choomz** [comment]
Hi,

There is no documentation for yaml mapping. Actually base class is managed by annotations. Maybe you can juste check rules here and convert your self to yaml.

https://github.com/V-labs/VlabsMediaBundle/blob/master/Entity/BaseFile.php
