### ISSUE TITLE
OneToMany association

### ISSUE THREAD

**Issue by grobx** [V-labs/VlabsMediaBundle#5]
Hi. I would like to know if this bundle is suitable for OneToMany associations.

**Comment by choomz** [comment]
Hi,

Can you share your mapping ?

I don't use it with OneToMany, but I have some projects wich are using ManyToMany associations and it's working, so it shouldbe ok ..

**Comment by grobx** [comment]
Sure, ill do.
Do you use it with SonataAdminBundle ?

**Comment by grobx** [comment]
[Here](https://github.com/silentinet/vlabs-onetomany-admin) you can find a live non-working example :)
If you need more info, please tell me.

**Comment by choomz** [comment]
Here is a not tested exemple : https://gist.github.com/choomz/4948099 but the mapping is correct.

I am not using Sonata's bundles. But i think there is a media bundle too if you want to use it with sonata admin.

**Comment by anyt** [comment]
Hi!
What FormType element do you use for multiple images upload with this bundle?

``` php
 $builder->add('images', 'vlabs_file', array(
                'required' => false
            );
```

This code isn't working for me.
And can I use http://blueimp.github.io/jQuery-File-Upload/ with this bundle?

**Comment by choomz** [comment]
Hi,

Actually, one input field = one file. The bundle is not working with ajax uploading and so, not working with multiple files upload with one field. It's in TODO :)

Note that you can have multiple fields in same form.
