### ISSUE TITLE
Not compatible with assets_version mechanism

### ISSUE THREAD

**Issue by jcrombez** [V-labs/VlabsMediaBundle#8]
When using the assets_version mechanism, i got the following error :

FatalErrorException: Error: Cannot use object of type Acme\HelloBundle\Entity\Avatar as array in /path/to/project/vendor/symfony/symfony/src/Symfony/Component/Templating/Asset/Package.php line 65

http://symfony.com/doc/master/reference/configuration/framework.html#ref-framework-assets-version

Symfony try to access the string as an array to reach the first character :

``` php
// line 65
if ($path && '/' == $path[0])
```

But VlabsMediaBundle only provide an Object and its ability to be converted to a string.
I guess we need to convert the object to a string sooner ourself, or add the ability to our object be accessed as an array.

**Comment by choomz** [comment]
Hi,

Can you post an example of you template ? Because the asset() function is supposed to be used with a string (a path), a so your template should call the avatar.path property.

I'll give a check to this.

**Comment by jcrombez** [comment]
{{ asset(topic.firstPost.author.avatar|vlabs_filter('crop', { 'width': 30, 'height': 30 })) }}

This work fine when not using the assets_version.

**Comment by choomz** [comment]
Indeed, you are right.  If you are using filters like this, you can't access the path. Could you try : 

```
{{ topic.firstPost.author.avatar|vlabs_filter('crop', { 'width': 30, 'height': 30 })|vlabs_media('image') }}
```

If you have not override the image view, it will work out of the box. You can check : 
https://github.com/V-labs/VlabsMediaBundle/blob/master/Resources/views/Templates/image.html.twig

Don't forget that you have to deal with your media properties in media templates, not in base templates.
This allow media templates to be reusable.

**Comment by jcrombez** [comment]
This :

``` html
{{ topic.lastPost.author.avatar|vlabs_filter('crop', { 'width': 30, 'height': 30 })|vlabs_media('image') }}
```

Become this :

``` html
<img src="/uploads/cache/crop/b1ad38ca31cd2bacc12330d4b5802396/6364d3f0f495b.png?v1">
```

And works.

But i need the path without the img tag.

**Comment by choomz** [comment]
Ok, so just use : 

```
{{ topic.firstPost.author.avatar|vlabs_filter('crop', { 'width': 30, 'height': 30 })|vlabs_media('default') }}
```

https://github.com/V-labs/VlabsMediaBundle/blob/master/Resources/views/Templates/default.html.twig

**Comment by jcrombez** [comment]
This is verbeux :p

**Comment by choomz** [comment]
This is the law ;)

**Comment by jcrombez** [comment]
Don't you think it would be a good thing to make a PR to Symfony to get the $path string casted before accessing it like an array ? I hesitate.

**Comment by choomz** [comment]
Hum actually I don't know, I need to check this ^^

But it depends on what you are trying to do. I don't think that Symfony is aware of the BaseFileInterface object, so there could be a way to deal with it into the bundle, but I need to check the use case.
